version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: app:gcisl
    container_name: gcisl_container
    command: python3 manage.py runserver 0.0.0.0:8000
