# Generated by Django 4.1.7 on 2023-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCISLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30, verbose_name='first')),
                ('last_name', models.CharField(max_length=30, verbose_name='last')),
                ('phone', models.CharField(help_text='Enter phone number, example: 1234567890', max_length=10, unique=True)),
                ('faculty', models.BooleanField(default=False)),
                ('resident', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
