# Generated by Django 4.1.7 on 2023-09-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGCISL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choiceid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='responseid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
