# Generated by Django 4.1.7 on 2023-04-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGCISL', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcisluser',
            name='location',
        ),
        migrations.AddField(
            model_name='gcisluser',
            name='image',
            field=models.ImageField(default='/static/assets/general/icon.png', upload_to='static/assets/general/'),
        ),
        migrations.AlterField(
            model_name='gcisluser',
            name='age_range',
            field=models.CharField(choices=[('1', '55-65'), ('2', '66-75'), ('3', '75+')], max_length=10, verbose_name='age'),
        ),
    ]
